### ISSUE TITLE
What is the use of test_indices.csv?

### ISSUE THREAD

**Issue by samarth-s-rao** [kwatcharasupat/query-bandit#3]
Just wanted to check in, in what way is test_indices.csv is used in the project, and if I am trying to work with a subset of moisesdb and not all the songs, can I still use the test_indices.csv provided here or do I need to make a custom one?

How do you go about making such a test_indices.csv

**Comment by kwatcharasupat** [comment]
This is to reproduce the test results as described in Section 4.3 of the paper. MoisesDB has no official split as of now. You can use `splits.csv` if you want to use the same folds as me.
