### ISSUE TITLE
Inference example

### ISSUE THREAD

**Issue by sonovice** [kwatcharasupat/query-bandit#4]
Hi Karn and thank you very much for your presentation at this year's ISMIR conference!

I would love to give your approach a try but am having issues to find some files and correct configurations. Could you please add a little documentation or simply an example on how to execute the model and query for a specific instrument? I have already found the models (https://zenodo.org/records/13694558) but putting it all together seems a little bit more involved.

Cheers!
Simon

**Comment by kwatcharasupat** [comment]
I just updated the repo. Please feel free to reopen the issue if you encounter any problem.
